{{- include "tenant.validate" . }}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: gitlab-token
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  refreshInterval: 5m
  secretStoreRef:
    kind: SecretStore
    name: tenant-vault
  data:
    - secretKey: token
      remoteRef:
        key: secrets/tenants/{{ .Values.tenant.username }}/gitlab-token
        property: value
  target:
    name: gitlab-token
    creationPolicy: Owner
