{{- include "tenant.validate" . }}
{{- $prefix := include "parasol-insurance-tenant.prefix" . -}}
{{- $role := include "tenant.vaultK8sRoleName" . -}}
{{- range $env := list "build" "dev" "prod" }}
---
apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: tenant-vault
  namespace: {{ $prefix }}-{{ $env }}
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  provider:
    vault:
      server: http://{{ $.Values.vault.name }}.{{ $.Values.vault.namespace }}.svc:8200
      path: kv
      version: v2
      auth:
        kubernetes:
          mountPath: kubernetes
          role: {{ $role }}
          serviceAccountRef:
            name: tenant-vault-reader
{{- end }}
{{- range $env := list "build" "dev" "prod" }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: tenant-vault-reader
  namespace: {{ $prefix }}-{{ $env }}
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
{{- end }}
