{{- range $tenant := .Values.tenants }}
{{- range $env := list "build" "dev" "prod" }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ $tenant }}-tenant-admin
  namespace: {{ $tenant }}-parasol-insurance-{{ $env }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ $.Values.clusterRole }}
subjects:
  - apiGroup: rbac.authorization.k8s.io
    kind: User
    name: {{ $tenant }}
{{- end }}
{{- end }}
